
*************************************************************************
*            PACKER92 - by David KÅhling 1997/98 - Header File          *
*-----------------------------------------------------------------------*
*  Archive: sample2.inc                                                 *
*************************************************************************


	;Archive type: PROGRAM DATA

String1 EQU 0
String2 EQU 24
String3 EQU 51
String4 EQU 80
String5 EQU 106
FormStr EQU 134
Num1 EQU 158
Num2 EQU 160
Buffer EQU 164