
*************************************************************************
*            PACKER92 - by David KÅhling 1997/98 - Header File          *
*-----------------------------------------------------------------------*
*  Archive: sample1.inc                                                 *
*************************************************************************


	Archive type: NORMAL

sample11_2bp EQU 0
sample11_2bpl EQU 7680
sample12_2bp EQU 1
sample12_2bpl EQU 7680
sample13_2bp EQU 2
sample13_2bpl EQU 7680
sample14_2bp EQU 3
sample14_2bpl EQU 7680
sample15_2bp EQU 4
sample15_2bpl EQU 7680
