;=============================================================================
; Include file automatically created by SHRINK92   Fri Jan  8 09:09:35 1999
; Purpose: access of archive `archive1.shk'
; That archive consists of 3 files in 3 sections.
;=============================================================================

PICTURE0.1PL       EQU       0  ; index of archive section
PICTURE0.1PL_LEN   EQU    3840  ; length of file
PICTURE1.1PL       EQU       1  ; index of archive section
PICTURE1.1PL_LEN   EQU    3840  ; length of file
PICTURE2.1PL       EQU       2  ; index of archive section
PICTURE2.1PL_LEN   EQU    3840  ; length of file
