;=============================================================================
; Include file automatically created by SHRINK92   Fri Jan  8 09:43:48 1999
; Purpose: access of archive `archive2.shk'
; That archive consists of 3 files in 1 section.
;=============================================================================

PICTURE0.1PL       EQU       0  ; offset of file in archive section #0
PICTURE0.1PL_LEN   EQU    3840  ; length of file
PICTURE1.1PL       EQU    3840  ; offset of file in archive section #0
PICTURE1.1PL_LEN   EQU    3840  ; length of file
PICTURE2.1PL       EQU    7680  ; offset of file in archive section #0
PICTURE2.1PL_LEN   EQU    3840  ; length of file
